-- debug.lua
--
-- Shows how to use the DAP plugin to debug your code.
-- Primarily focused on configuring the debugger for Go.
--
-- NOTE: These plugins are not currently installed via vim.pack.
-- To enable debugging, add the following to the vim.pack.add() call in init.lua:
--   'https://github.com/mfussenegger/nvim-dap',
--   'https://github.com/rcarriga/nvim-dap-ui',
--   'https://github.com/nvim-neotest/nvim-nio',
--   'https://github.com/jay-babu/mason-nvim-dap.nvim',
--   'https://github.com/leoluz/nvim-dap-go',
-- Then add the setup calls below and require this file from init.lua.
--
-- local dap = require 'dap'
-- local dapui = require 'dapui'
-- require('mason-nvim-dap').setup({ automatic_installation = true, handlers = {}, ensure_installed = { 'delve' } })
-- dapui.setup({ icons = { expanded = '▾', collapsed = '▸', current_frame = '*' } })
-- dap.listeners.after.event_initialized['dapui_config'] = dapui.open
-- dap.listeners.before.event_terminated['dapui_config'] = dapui.close
-- dap.listeners.before.event_exited['dapui_config'] = dapui.close
-- require('dap-go').setup({ delve = { detached = vim.fn.has 'win32' == 0 } })
-- vim.keymap.set('n', '<F5>', function() dap.continue() end, { desc = 'Debug: Start/Continue' })
-- vim.keymap.set('n', '<F1>', function() dap.step_into() end, { desc = 'Debug: Step Into' })
-- vim.keymap.set('n', '<F2>', function() dap.step_over() end, { desc = 'Debug: Step Over' })
-- vim.keymap.set('n', '<F3>', function() dap.step_out() end, { desc = 'Debug: Step Out' })
-- vim.keymap.set('n', '<leader>b', function() dap.toggle_breakpoint() end, { desc = 'Debug: Toggle Breakpoint' })
-- vim.keymap.set('n', '<leader>B', function() dap.set_breakpoint(vim.fn.input 'Breakpoint condition: ') end, { desc = 'Debug: Set Breakpoint' })
-- vim.keymap.set('n', '<F7>', function() dapui.toggle() end, { desc = 'Debug: See last session result.' })
