-- Adds git related signs to the gutter, as well as utilities for managing changes.
-- This config mirrors lua/custom/plugins/gitsigns.lua which is the active source of truth.
-- Kept here as a reference. The active setup is loaded via require 'custom.plugins.gitsigns'.
