-- Neo-tree is a Neovim plugin to browse the file system
-- https://github.com/nvim-neo-tree/neo-tree.nvim
--
-- NOTE: This plugin is not currently installed via vim.pack.
-- The active file explorer is Snacks.explorer (snacks.nvim).
-- To enable neo-tree, add the following to the vim.pack.add() call in init.lua:
--   'https://github.com/nvim-neo-tree/neo-tree.nvim',
--   'https://github.com/MunifTanjim/nui.nvim',
-- Then add the setup call below and require this file from init.lua.
--
-- require('neo-tree').setup({
--   filesystem = {
--     window = {
--       mappings = { ['\\'] = 'close_window' },
--     },
--   },
-- })
-- vim.keymap.set('n', '\\', ':Neotree reveal<CR>', { desc = 'NeoTree reveal', silent = true })
